### ISSUE TITLE
Foto do pierwszej Aktualności + pierwszy film na budrank.tv

### ISSUE THREAD

**Issue by dev999seo** [LaaHudra/budrank#15]
Photo: http://www.shutterstock.com/pl/pic-104931227/stock-photo-image-of-road-with-white-arrow-directing-forward.html?src=BksLlZW4RGx6OhZcQqGawQ-3-86
Movie: http://www.youtube.com/watch?v=8Ja_Noc2WTY lub https://www.youtube.com/watch?v=pNK5xPHPRv8

**Comment by LaaHudra** [comment]
http://test.budrank.pl/budrank_tv

Potrzebny mi tekst zamiast lorem ipsum krotki opis chyba filmu.

**Comment by dev999seo** [comment]
Zaciągnij lub skopiuj z yt

**Comment by LaaHudra** [comment]
Chcesz wiedzieć jak uzyskać pozwolenie na budowę?

Na tym filmie wyjaśnię Ci krok po kroku jakie instytucje będziesz musiał odwiedzić oraz w jakiej kolejności. Dodatkowo zobaczysz skany dokumentów jakie otrzymasz w Zakładzie Wodociągów, Energetyce, Biurze Projektowym, Urzędzie Miasta oraz w Wydziale Architektoniczno-Budowlanym.

to jest na yt i trzeba to przeredagowac.

**Comment by dev999seo** [comment]
Uzyskanie pozwolenia na budowę nie należy do najprostszych spraw związanych z budową domu, jednak jest jedną z pierwszych i niezbędnych rzeczy, jakie musimy pozyskać, aby zacząć działać na budowe. Film wyjaśnia krok po kroku, co zrobić i w jakiej kolejności, aby pozwolenia znalazło się w naszych rękach.

**Comment by dev999seo** [comment]
Done
