### ISSUE TITLE
Zmienić tekst pierwszej aktualności

### ISSUE THREAD

**Issue by dev999seo** [LaaHudra/budrank#19]
Znajduje się w pliku na google drive (ten sam w którym jest aktualność obecna)

**Comment by LaaHudra** [comment]
To nie mozna dac linka?

**Comment by LaaHudra** [comment]
- udostepnij mi folder

**Comment by dev999seo** [comment]
Po prostu wklej to:

<p>Nadszedł już czas, kiedy rusza nowa jakość na rynku budowlanym! Wiemy, że w dzisiejszych czasach, kiedy jesteśmy zabiegani, często nie znamy realiów budownictwa. Ile razy mieliście problem z fachowcami? Jak często Twój remont okazał się drogą przez mękę, a budowa stała w miejscu? Pewnie nie raz. Z nami ten problem zniknie! To tutaj możesz sprawdzić rzetelność fachowca, a on Twoją. Przecież najbardziej obiektywna opinia to zdanie poprzednich zleceniodawców i oferentów. To oni poprzez swoje oceny i osądy pomogą Ci wybrać odpowiednią firmę. Właśnie dzięki nam dodatkowo skrócisz ten czas! Bez wychodzenia z domu wybierz najlepszą ofertę i zacznij działać!</p>

**Comment by dev999seo** [comment]
Done
