### ISSUE TITLE
Treści na stronę główną

### ISSUE THREAD

**Issue by dev999seo** [LaaHudra/budrank#27]
Serwis w prosty i szybki sposób ma pomóc w znalezieniu partnera w branży budowlanej oraz ma na celu dostarczenie kompleksowej informacji na temat każdego wykonawcy oraz inwestora w naszej bazie. Opiera się ona na rozbudowanym rankingu przedsiębiorstw, opartym na ocenie inwestorskiej i wykonawczej.
Strona dostarcza również bieżące informacje z rynku budowlanego oraz nowości w serwisie Budrank.pl. Ponad to przedstawia ciekawe filmy, które są związane z branżą budowlaną.

Misja: Naszym zadaniem jest dostarczyć użytkownikom serwisu najlepszą oraz pełną informację o przyszłym, najbardziej konkurencyjnym partnerze budowlanym oraz jak najlepiej pomóc w jego wyborze poprzez, jak najszybsze oraz rzetelne kojarzenie stron, które mają wspólne cele - zlecić pracę budowlaną i ją wykonać.

Wizja: Stać się wiodącym serwisem w branży budowlanej, zgromadzić najobszerniejszą bazę informacji i ocen o wykonawcach budowlanych oraz inwestorach, dostarczać największą liczbę ofert budowlanych na rynek, które znajdą swojego wykonawcę.

**Comment by dev999seo** [comment]
Remontuj.pl ma w stopce "O nas" można zrobić coś podobnego.

**Comment by LaaHudra** [comment]
Ok
a w srodku co?

2014-11-24 18:02 GMT+01:00 dev999seo notifications@github.com:

**Comment by dev999seo** [comment]
Jak w srodku nic nie zmiescisz to daj wszystko na dole. W stodku jak juz to najkrotsze teksty.

Dnia 24 lis 2014 o godz. 18:17 Michał Tajchert notifications@github.com napisał(a):

**Comment by dev999seo** [comment]
"O BUDRANK.PL" a nie "O budrank.pl"
Słowo Misja i Wizja pogrubione.
Cały ten tekst będzie lepiej wyglądał pod Najpopularniejszymi branżami.
Napisz "Najpopularniejsze branże budowlane" a nie samo "Najpopularniejsze branże"
Na stronie głównej gdzieś przy sylwetce pana Wojciecha: "Znajdź z nami najlepszego wykonawcę!"
Przy sylwetce Pana Marka: "Znajdź z nami najlepszego inwestora!"
Między najpopularniejsze branże budowlane a banerem:
<b>Inwestorze</b> - po co wychodzić z domu żeby znaleźć odpowiedniego wykonawcę? Nie dzwoń do znajomych, nie pytaj w sklepach budowlanych. Pozwól, że zrobimy to za Ciebie! Dodaj zlecenie po zalogowaniu się do naszego serwisu. Napisz co konkretnie chcesz zrobić w swoim mieszkaniu, czy domu, wybierz kategorię prac, podaj lokalizację oraz możliwy termin rozpoczęcia. Łatwo, krok po kroku wypełnij pola w naszym formularzu dodawania zlecenia. Poczekaj chwilę, a ktoś na pewno się zgłosi! Nie chcesz czekać? Napisz do firmy z naszej listy, która Cię interesuje. Nie wiesz którą firmę wybrać? Spójrz na obiektywny Ranking, który przygotowaliśmy specjalnie dla Ciebie! Nic prostszego.
<b>Wykonawco</b> - nie chcesz czekać na telefony i żmudne opisywanie kolejnych zleceń? Zaloguj się do naszego serwisu, sprawdzaj dokładnie opisane zadania budowlane i wybierz te które Cię interesują. Nie chcesz oglądać wszystkich? Zaznacz konkretną branżę w której działasz i przeglądaj zlecenia. Nie chcesz dzwonić? Złóż swoją konkurencyjną ofertę w oknach Giełdy zleceń, a na pewno dostarczymy ją za Ciebie poprzez nasz serwis. Bądź na bieżąco! Zlecenia pojawiają się częściej niż dzwoni Twój telefon.

**Comment by dev999seo** [comment]
Jak teraz nie starczy to kurwa nie wiem
