### ISSUE TITLE
Dodawanie zlecenia

### ISSUE THREAD

**Issue by dev999seo** [LaaHudra/budrank#28]
W dodawaniu zlecenia musi być napis: "Czas wyświetlania w serwisie" albo to wyjebać w ogóle bo z automatu nam wywala zlecenia a ludzie zapominają. Niech usuwają osobno w profilu.

**Comment by LaaHudra** [comment]
jak wywala zlecenia?

2014-11-25 14:12 GMT+01:00 dev999seo notifications@github.com:

**Comment by LaaHudra** [comment]
ja nie rozumiem w sumie co Ty chcesz mi rpzekazac.

**Comment by dev999seo** [comment]
W dodawaniu zlecenia jest "czas trwania" - po pierwsze jest to niezrozumiałe bo nie wiadomo czy chodzi o czas trwania pracy wykonawcy czy czas trwania zlecenia w serwisie. Moim zdaniem albo trzeba to zmienic na "Czas wyświetlania w serwisie" albo lepiej usunąć tę funkcję i niech sami usuwają zlecenia z poziomu profilu bo później same nam znikają po czasie który wskażą przez tę funkcję. Rozumiesz?
